path: /Users/asinghal/PycharmProjects/ObjectDetection/data/processed
train: images/sample_train
val: images/sample_val

names:
  0: aeroplane
  1: ashtray
  2: backpack
  3: basket
  4: bed
  5: bench
  6: bicycle
  7: blackboard
  8: boat
  9: bookshelf
  10: bottle
  11: bucket
  12: bus
  13: cabinet
  14: calculator
  15: camera
  16: can
  17: cap
  18: car
  19: cellphone
  20: chair
  21: clock
  22: coffee_maker
  23: comb
  24: computer
  25: cup
  26: desk_lamp
  27: diningtable
  28: dishwasher
  29: door
  30: eraser
  31: eyeglasses
  32: fan
  33: faucet
  34: filing_cabinet
  35: fire_extinguisher
  36: fish_tank
  37: flashlight
  38: fork
  39: guitar
  40: hair_dryer
  41: hammer
  42: headphone
  43: helmet
  44: iron
  45: jar
  46: kettle
  47: key
  48: keyboard
  49: knife
  50: laptop
  51: lighter
  52: mailbox
  53: microphone
  54: microwave
  55: motorbike
  56: mouse
  57: paintbrush
  58: pan
  59: pen
  60: pencil
  61: piano
  62: pillow
  63: plate
  64: pot
  65: printer
  66: racket
  67: refrigerator
  68: remote_control
  69: rifle
  70: road_pole
  71: satellite_dish
  72: scissors
  73: screwdriver
  74: shoe
  75: shovel
  76: sign
  77: skate
  78: skateboard
  79: slipper
  80: sofa
  81: speaker
  82: spoon
  83: stapler
  84: stove
  85: suitcase
  86: teapot
  87: telephone
  88: toaster
  89: toilet
  90: toothbrush
  91: train
  92: trash_bin
  93: trophy
  94: tub
  95: tvmonitor
  96: vending_machine
  97: washing_machine
  98: watch
  99: wheelchair